---
version: 2.1

orbs:
  node: circleci/node@4.0.0

defaults: &defaults
  working_directory: ~/monorepo

commands: 
  init:
    steps:
      - checkout
      - restore_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          
  install_lerna: 
    steps:
      - run: |
          npm install lerna
  package: 
    steps:
      - run: |
          npm install
  bootstrap: 
    steps:
      - run: |
          npm install lerna
          npx lerna bootstrap
  test: 
    steps:
      - run: |
          npx lerna run test --since HEAD~1
jobs:
  itegration: 
    <<: *defaults

    resource_class: medium
    machine: true

    steps:
      - init

      - package

      - install_lerna

      - bootstrap

      - test


workflows:
  version: 2

  everything: 
    jobs:
      - itegration


